#!/bin/zsh

set -e

# link to $HOME and cd to it
cd ..
cp -rf dotfiles "$HOME/.dotfiles"
cd "$HOME/.dotfiles"

# bootstrap the mighty
echo "boostraping..."
./script/bootstrap

# load zshrc and check if antidote is working
echo "sourcing $HOME/.zshrc"
# shellcheck disable=SC1090
source "$HOME/.zshrc" || true

test "$(antidote list | wc -l)" -gt 6 || {
	echo "expecting 6+ bundles loaded" >&2
	exit 1
}

test -s "$HOME/.zcompdump" || {
	echo "zcompdump file is empty" >&2
	exit 1
}

# TODO: check if a random plugin is working (meaning that the bundles were loaded)
