#!/usr/bin/env zsh

SPACESHIP_PROMPT_ORDER=(
  user
  dir
  golang
  venv
  exec_time
  line_sep
  char
)

SPACESHIP_RPROMPT_ORDER=(
  git
  host
)

SPACESHIP_CHAR_SYMBOL="|>"
SPACESHIP_CHAR_SYMBOL_ROOT="|>"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS=15
SPACESHIP_CHAR_COLOR_FAILURE=203

SPACESHIP_USER_SHOW="always"
SPACESHIP_USER_COLOR=38
SPACESHIP_USER_COLOR_ROOT=203

SPACESHIP_HOST_PREFIX="on "
SPACESHIP_HOST_COLOR_SSH=38

SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_COLOR=214
SPACESHIP_DIR_LOCK_COLOR=203
SPACESHIP_DIR_PREFIX=""

SPACESHIP_GIT_BRANCH_COLOR=214
SPACESHIP_GIT_STATUS_COLOR=203

SPACESHIP_GOLANG_PREFIX="["
SPACESHIP_GOLANG_SUFFIX="] "
SPACESHIP_GOLANG_SYMBOL="golang:"
SPACESHIP_GOLANG_COLOR=81

SPACESHIP_VENV_PREFIX="["
SPACESHIP_VENV_SUFFIX="] "
SPACESHIP_VENV_SYMBOL="venv:"
SPACESHIP_VENV_COLOR=220

SPACESHIP_EXEC_TIME_COLOR=214
